[package]
name = "hbcn_constrainer"
version = "0.1.0"
authors = ["Marcos Sartori <marcos.sartori@acad.pucrs.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "^0.19.2"

[features]
embedded_cbc = ["coin_cbc/embedded_cbc"]

[dependencies]
petgraph = "~0.4.13"
lalrpop-util = "~0.19.2"
regex = "^1.4.2"
clap = "^2.33.3"
string_cache = "~0.8.1"
coin_cbc = { git = "https://github.com/marlls1989/coin_cbc" }
gurobi = "~0.3.4"
gag = "~0.1.10"
vcd = "~0.6.1"
itertools = "~0.10.0"
lazy_static = "~1.4.0"
rayon = "~1.5.0"

