[package]
authors = ["Marcos Sartori <marcos.sartori@acad.pucrs.br>"]
edition = "2018"
name = "hbcn"
version = "0.1.1"
[build-dependencies]
lalrpop = "^0.19.2"

[dependencies]
clap = "^2.33.3"
lalrpop-util = "~0.19.2"
petgraph = "~0.5.1"
regex = "^1.4.2"
string_cache = "~0.8.1"
structopt = "*"
gurobi = "~0.3.4"
vcd = "~0.6.1"
lazy_static = "~1.4.0"
itertools = "~0.10.0"
rayon = "~1.5.0"
gag = "~0.1.10"
prettytable-rs = "~0.8.0"
