[package]
name = "hbcn_constrainer"
version = "0.1.0"
authors = ["Marcos Sartori <msartori@thesiriusproject.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
