name: CI

# This workflow uses a custom Docker container with CBC dependencies pre-installed
# to avoid downloading and installing system packages on every CI run.

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  CI_IMAGE: ghcr.io/${{ github.repository }}-ci:latest

jobs:
  build-ci-image:
    name: Build CI Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.image.outputs.image }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.ci
        push: true
        tags: ${{ env.CI_IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Output image name
      id: image
      run: echo "image=${{ env.CI_IMAGE }}" >> $GITHUB_OUTPUT

  test:
    needs: build-ci-image
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_IMAGE }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root  # Needed for some GitHub Actions
    
    strategy:
      matrix:
        rust:
          - 1.85.0
          - stable
          - beta
          - nightly
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/cargo/registry
          /usr/local/cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Check formatting
      run: cargo fmt --all -- --check
      if: matrix.rust == 'stable'
    
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      if: matrix.rust == 'stable'
